(require '+autoload)
(require '+config)
(require 'init-package)
(require 'init-basic)
(require 'init-ui)
(require 'init-keybind)
(require 'init-tools)
(require 'init-complete)
(require 'init-prog)
(require 'init-org)
(require 'init-dired)
(require 'init-version-control)
(require 'init-ivy)
(require 'init-projectile)


(provide 'init-config)
